[deps]
ACE1 = "e3f9bc04-086e-409a-ba78-e9769fe067bb"
ACEpotentials = "3b96b61c-0fcc-4693-95ed-1ef9f35fcc53"
ASE = "51974c44-a7ed-5088-b8be-3e78c8ba416c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ExtXYZ = "352459e4-ddd7-4360-8937-99dcb397b478"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
extxyz_jll = "6ecdc6fc-93a8-5528-aee3-ac7ae1c60be7"
